// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/grpcdemo/grpcdemo.proto

package grpcdemo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcDemoService_Ping_FullMethodName           = "/grpcdemo.GrpcDemoService/Ping"
	GrpcDemoService_StreamMessages_FullMethodName = "/grpcdemo.GrpcDemoService/StreamMessages"
)

// GrpcDemoServiceClient is the client API for GrpcDemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A simple demo service with Ping and streaming RPCs.
type GrpcDemoServiceClient interface {
	// Unary: returns a pong with the same message.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	// Bidirectional streaming: echoes a reply for every incoming stream message.
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamReply], error)
}

type grpcDemoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcDemoServiceClient(cc grpc.ClientConnInterface) GrpcDemoServiceClient {
	return &grpcDemoServiceClient{cc}
}

func (c *grpcDemoServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, GrpcDemoService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDemoServiceClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GrpcDemoService_ServiceDesc.Streams[0], GrpcDemoService_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrpcDemoService_StreamMessagesClient = grpc.BidiStreamingClient[StreamRequest, StreamReply]

// GrpcDemoServiceServer is the server API for GrpcDemoService service.
// All implementations must embed UnimplementedGrpcDemoServiceServer
// for forward compatibility.
//
// A simple demo service with Ping and streaming RPCs.
type GrpcDemoServiceServer interface {
	// Unary: returns a pong with the same message.
	Ping(context.Context, *PingRequest) (*PingReply, error)
	// Bidirectional streaming: echoes a reply for every incoming stream message.
	StreamMessages(grpc.BidiStreamingServer[StreamRequest, StreamReply]) error
	mustEmbedUnimplementedGrpcDemoServiceServer()
}

// UnimplementedGrpcDemoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcDemoServiceServer struct{}

func (UnimplementedGrpcDemoServiceServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGrpcDemoServiceServer) StreamMessages(grpc.BidiStreamingServer[StreamRequest, StreamReply]) error {
	return status.Error(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedGrpcDemoServiceServer) mustEmbedUnimplementedGrpcDemoServiceServer() {}
func (UnimplementedGrpcDemoServiceServer) testEmbeddedByValue()                         {}

// UnsafeGrpcDemoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcDemoServiceServer will
// result in compilation errors.
type UnsafeGrpcDemoServiceServer interface {
	mustEmbedUnimplementedGrpcDemoServiceServer()
}

func RegisterGrpcDemoServiceServer(s grpc.ServiceRegistrar, srv GrpcDemoServiceServer) {
	// If the following call panics, it indicates UnimplementedGrpcDemoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcDemoService_ServiceDesc, srv)
}

func _GrpcDemoService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDemoServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcDemoService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDemoServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDemoService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcDemoServiceServer).StreamMessages(&grpc.GenericServerStream[StreamRequest, StreamReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrpcDemoService_StreamMessagesServer = grpc.BidiStreamingServer[StreamRequest, StreamReply]

// GrpcDemoService_ServiceDesc is the grpc.ServiceDesc for GrpcDemoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcDemoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcdemo.GrpcDemoService",
	HandlerType: (*GrpcDemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GrpcDemoService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _GrpcDemoService_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/grpcdemo/grpcdemo.proto",
}
