// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/grpcdemo/grpcdemo.proto

package grpcdemo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_grpcdemo_grpcdemo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcdemo_grpcdemo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_proto_grpcdemo_grpcdemo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcdemo_grpcdemo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_proto_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_grpcdemo_grpcdemo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcdemo_grpcdemo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReply) Reset() {
	*x = StreamReply{}
	mi := &file_proto_grpcdemo_grpcdemo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReply) ProtoMessage() {}

func (x *StreamReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcdemo_grpcdemo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReply.ProtoReflect.Descriptor instead.
func (*StreamReply) Descriptor() ([]byte, []int) {
	return file_proto_grpcdemo_grpcdemo_proto_rawDescGZIP(), []int{3}
}

func (x *StreamReply) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_grpcdemo_grpcdemo_proto protoreflect.FileDescriptor

const file_proto_grpcdemo_grpcdemo_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/grpcdemo/grpcdemo.proto\x12\bgrpcdemo\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\tPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\rStreamRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\vStreamReply\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8b\x01\n" +
	"\x0fGrpcDemoService\x122\n" +
	"\x04Ping\x12\x15.grpcdemo.PingRequest\x1a\x13.grpcdemo.PingReply\x12D\n" +
	"\x0eStreamMessages\x12\x17.grpcdemo.StreamRequest\x1a\x15.grpcdemo.StreamReply(\x010\x01B\x17Z\x15demo-app/pkg/grpcdemob\x06proto3"

var (
	file_proto_grpcdemo_grpcdemo_proto_rawDescOnce sync.Once
	file_proto_grpcdemo_grpcdemo_proto_rawDescData []byte
)

func file_proto_grpcdemo_grpcdemo_proto_rawDescGZIP() []byte {
	file_proto_grpcdemo_grpcdemo_proto_rawDescOnce.Do(func() {
		file_proto_grpcdemo_grpcdemo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpcdemo_grpcdemo_proto_rawDesc), len(file_proto_grpcdemo_grpcdemo_proto_rawDesc)))
	})
	return file_proto_grpcdemo_grpcdemo_proto_rawDescData
}

var file_proto_grpcdemo_grpcdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_grpcdemo_grpcdemo_proto_goTypes = []any{
	(*PingRequest)(nil),   // 0: grpcdemo.PingRequest
	(*PingReply)(nil),     // 1: grpcdemo.PingReply
	(*StreamRequest)(nil), // 2: grpcdemo.StreamRequest
	(*StreamReply)(nil),   // 3: grpcdemo.StreamReply
}
var file_proto_grpcdemo_grpcdemo_proto_depIdxs = []int32{
	0, // 0: grpcdemo.GrpcDemoService.Ping:input_type -> grpcdemo.PingRequest
	2, // 1: grpcdemo.GrpcDemoService.StreamMessages:input_type -> grpcdemo.StreamRequest
	1, // 2: grpcdemo.GrpcDemoService.Ping:output_type -> grpcdemo.PingReply
	3, // 3: grpcdemo.GrpcDemoService.StreamMessages:output_type -> grpcdemo.StreamReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grpcdemo_grpcdemo_proto_init() }
func file_proto_grpcdemo_grpcdemo_proto_init() {
	if File_proto_grpcdemo_grpcdemo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpcdemo_grpcdemo_proto_rawDesc), len(file_proto_grpcdemo_grpcdemo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpcdemo_grpcdemo_proto_goTypes,
		DependencyIndexes: file_proto_grpcdemo_grpcdemo_proto_depIdxs,
		MessageInfos:      file_proto_grpcdemo_grpcdemo_proto_msgTypes,
	}.Build()
	File_proto_grpcdemo_grpcdemo_proto = out.File
	file_proto_grpcdemo_grpcdemo_proto_goTypes = nil
	file_proto_grpcdemo_grpcdemo_proto_depIdxs = nil
}
