apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-app-ds-v0
  namespace: clusterfleet
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-app-ds-v0
  template:
    metadata:
      labels:
        app: demo-app-ds-v0
        test: "6"
    spec:
      hostNetwork: true
      containers:
      - args:
          - --http-port
          - "12011"
          - --startup-delay
          - "0"
        env:
        - name: TIMESTAMP
          value: "DEPLOYMENT_TIMESTAMP"
        envFrom:
        - configMapRef:
            name: clusterfleet-config
        image: demo-app:DEPLOYMENT_IMAGE_VERSION
        name: demo-app-ds-v0
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /keepalive
            port: 12011
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ready
            port: 12011
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 2
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-sock
