apiVersion: apis.clusterfleet.io/v1alpha1
kind: Application
metadata:
  annotations:
    microsoft-falcon.net/clusterip-check: "disabled"
    microsoft-falcon.net/falcon-core-service: "false"
  name: demo-app-rwpr
  namespace: clusterfleet
spec:
  version: "DEPLOYMENT_APP_VERSION"
  schedulingStrategy:
    preferredSliceStrategy:
      minSlice: 3
      minSliceSize: 30
    slicePreference: NoSlice
  rolloutStrategy:
    type: ReplicasWeightedProgressiveRollout
    replicasWeightedProgressiveRollout:
      rollingWindowSizeLimit: 2
  workload:
    - manifest:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: demo-app
          namespace: clusterfleet
        spec:
          updateStrategy:
            rollingUpdate:
              maxSurge: 0
              maxUnavailable: 10%
            type: RollingUpdate
          replicas: 7
          selector:
            matchLabels:
              app: demo-app-rwpr
          serviceName: ""
          template:
            metadata:
              labels:
                app: demo-app-rwpr
                test: "6"
            spec:
              containers:
              - args:
                  - --http-port
                  - "12012"
                  - --startup-delay
                  - "2"
                env:
                - name: TIMESTAMP
                  value: "DEPLOYMENT_TIMESTAMP"
                envFrom:
                - configMapRef:
                    name: clusterfleet-config
                image: demo-app:DEPLOYMENT_IMAGE_VERSION
                name: demo-app-rwpr
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /keepalive
                    port: 12012
                    scheme: HTTP
                  initialDelaySeconds: 2
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 2
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /ready
                    port: 12012
                    scheme: HTTP
                  initialDelaySeconds: 2
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 2
                resources:
                  requests:
                    cpu: 1200m
                    memory: 128Mi
                  limits:
                    cpu: 1200m
                    memory: 256Mi
              dnsPolicy: ClusterFirst
              restartPolicy: Always
              nodeSelector:
                kubernetes.io/os: linux
                scheduler.clusterfleet.io/ready: "true"
                kubernetes.azure.com/mode: "user"
