apiVersion: apis.clusterfleet.io/v1alpha1
kind: Application
metadata:
  annotations:
    microsoft-falcon.net/clusterip-check: "disabled"
    microsoft-falcon.net/falcon-core-service: "true"
  name: demo-app-ds
  namespace: clusterfleet
spec:
  version: "DEPLOYMENT_APP_VERSION"
  rolloutStrategy:
    progressiveRollout:
      progressiveRolloutWindowSize: "3"
      perClusterMinimumAvailableReplicasPct: 99%
      perClusterRolloutDeadlineSeconds: 150
      maxAllowedClustersPastDeadline: 10%
  workload:
    # - manifest:
    #     apiVersion: v1
    #     kind: Service
    #     metadata:
    #       name: demo-app-ds-lb-service-2
    #       namespace: clusterfleet
    #       labels:
    #         app: demo-app-ds
    #     spec:
    #       type: LoadBalancer
    #       ports:
    #       - port: 11012
    #         targetPort: http
    #         protocol: TCP
    #       selector:
    #         app: demo-app-ds
    # - manifest:
    #     apiVersion: v1
    #     kind: Service
    #     metadata:
    #       name: demo-app-ds-clusterip-service
    #       namespace: clusterfleet
    #       labels:
    #         app: demo-app-ds
    #     spec:
    #       type: ClusterIP
    #       selector:
    #         app: demo-app-ds
    - manifest:
        apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          name: demo-app-ds
          namespace: clusterfleet
        spec:
          updateStrategy:
            rollingUpdate:
              maxUnavailable: 1
            type: RollingUpdate
          selector:
            matchLabels:
              app: demo-app-ds
          serviceName: ""
          template:
            metadata:
              labels:
                app: demo-app-ds
            spec:
              containers:
              - args:
                  - --http-port
                  - "12012"
                  - --startup-delay
                  - "0"
                env:
                - name: TIMESTAMP
                  value: "DEPLOYMENT_TIMESTAMP"
                envFrom:
                - configMapRef:
                    name: clusterfleet-config
                image: demo-app:DEPLOYMENT_IMAGE_VERSION
                name: demo-app-ds
                ports:
                - containerPort: 12012
                  name: http
                  protocol: TCP
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /keepalive
                    port: 12012
                    scheme: HTTP
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 2
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /ready
                    port: 12012
                    scheme: HTTP
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 2
                resources:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 100m
                    memory: 256Mi
              nodeSelector:
                kubernetes.io/os: linux
                scheduler.clusterfleet.io/ready: "true"
                kubernetes.azure.com/mode: "user"
              dnsPolicy: ClusterFirst
              restartPolicy: Always
